// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr22GfKm1wYIqiEzkuJQ9S9Rr5xWpAeGE',
    appId: '1:555903740115:web:5908f0f2c7f904e65c8c26',
    messagingSenderId: '555903740115',
    projectId: 'zenorganizer-2afb2',
    authDomain: 'zenorganizer-2afb2.firebaseapp.com',
    storageBucket: 'zenorganizer-2afb2.appspot.com',
    measurementId: 'G-LCG8ZS272Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpC6Up6GxEdh67yVW1gHqtEHXb9-zqqSM',
    appId: '1:555903740115:android:d2473f77bb765f9d5c8c26',
    messagingSenderId: '555903740115',
    projectId: 'zenorganizer-2afb2',
    storageBucket: 'zenorganizer-2afb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wJgnspc87Lmy4gAs0ROGhd1m0SSoD5M',
    appId: '1:555903740115:ios:45c26ac062478fb25c8c26',
    messagingSenderId: '555903740115',
    projectId: 'zenorganizer-2afb2',
    storageBucket: 'zenorganizer-2afb2.appspot.com',
    iosBundleId: 'com.example.zenOrganizer',
  );
}
